version: '3.0'

services:
  nginx:
    image: nginx:1.15.2-alpine # smaller image
    ports: 
      - "8080:443"
    volumes:
      - ./index.html:/var/data/content/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/var/data/cert.pem # nginx.conf points to these
      - ./key.pem:/var/data/key.pem
    command: [nginx-debug, '-g', 'daemon off;']
  nodeserver:
    image: node:10-slim
    expose:
      - 3000
    volumes:
      - ./:/workdir
    command: [node, '/workdir/index.js']
